"""Markdown report generation for PromoLab."""

from __future__ import annotations

import pandas as pd


def _fmt_number(value: float) -> str:
    return f"{value:,.2f}"


def _fmt_percent(value: float | None) -> str:
    if value is None:
        return "n/a"
    return f"{value * 100:.2f}%"


def _metric_label(metric: str) -> str:
    labels = {
        "revenue": "Revenue",
        "orders": "Orders",
        "transactions": "Transactions",
        "aov": "AOV",
        "discount_rate": "Discount rate",
        "refund_rate": "Refund rate",
        "gross_profit": "Gross profit",
    }
    return labels.get(metric, metric.replace("_", " ").title())


def generate_markdown_report(
    promo_start: pd.Timestamp,
    promo_end: pd.Timestamp,
    baseline_method: str,
    lift: dict[str, dict[str, float | None]],
    drivers: pd.DataFrame,
    warnings: list[str],
    ai_explanation: str | None = None,
    cannibalization_summary: dict[str, float | bool] | None = None,
) -> str:
    """Create a clean, skimmable Markdown promo report."""
    method_label = {
        "matched_4w": "Matched weekdays (previous 4 weeks)",
        "last_28d": "Last 28 days",
        "custom": "Custom baseline",
    }.get(baseline_method, baseline_method)

    lines: list[str] = []
    lines.append("# Promo Report")
    lines.append("")
    lines.append("## Analysis scope")
    lines.append(f"- **Promo window:** {promo_start.strftime('%Y-%m-%d')} to {promo_end.strftime('%Y-%m-%d')}")
    lines.append(f"- **Baseline method:** {method_label}")
    lines.append("")

    lines.append("## KPI summary")
    lines.append("")
    lines.append("| KPI | Promo | Baseline | Lift (abs) | Lift (%) |")
    lines.append("|---|---:|---:|---:|---:|")
    for metric in ["revenue", "orders", "transactions", "aov", "discount_rate", "refund_rate", "gross_profit"]:
        item = lift.get(metric)
        if item is None:
            continue
        lines.append(
            "| "
            f"{_metric_label(metric)} | "
            f"{_fmt_number(float(item['promo']))} | "
            f"{_fmt_number(float(item['baseline']))} | "
            f"{_fmt_number(float(item['abs_change']))} | "
            f"{_fmt_percent(item['pct_change'] if isinstance(item['pct_change'], float) else None)} |"
        )
    lines.append("")

    lines.append("## Top 5 drivers (Δ revenue by item)")
    lines.append("")
    if drivers.empty:
        lines.append("- No item-level drivers available.")
    else:
        top = drivers.head(5)
        for _, row in top.iterrows():
            lines.append(
                f"- **{row['item_name']}**: Δ revenue `{_fmt_number(float(row['delta_revenue']))}` "
                f"(promo `{_fmt_number(float(row.get('promo_revenue', 0.0)))}`, "
                f"baseline-adj `{_fmt_number(float(row.get('baseline_for_promo_days', 0.0)))}`)"
            )
    lines.append("")

    if cannibalization_summary:
        lines.append("## Pull-forward / cannibalization check")
        lines.append("")
        lines.append(
            "- Promo revenue: "
            f"`{_fmt_number(float(cannibalization_summary.get('promo_actual', 0.0)))}` "
            f"vs expected `{_fmt_number(float(cannibalization_summary.get('promo_expected', 0.0)))}`"
        )
        lines.append(
            "- Post 7-day revenue: "
            f"`{_fmt_number(float(cannibalization_summary.get('post_actual', 0.0)))}` "
            f"vs expected `{_fmt_number(float(cannibalization_summary.get('post_expected', 0.0)))}`"
        )
        lines.append(
            "- Pull-forward risk flag: "
            f"`{'YES' if bool(cannibalization_summary.get('risk_flag')) else 'NO'}`"
        )
        lines.append("")

    lines.append("## Interpretation rules")
    lines.append("")
    lines.append("- If **revenue lift > 0** and **orders lift > 0**, volume likely increased.")
    lines.append("- If **revenue lift > 0** but **orders flat/down** and **AOV up**, basket size/pricing likely drove gains.")
    lines.append("- Rising **discount rate** with weak revenue lift can indicate inefficient promo spend.")
    lines.append("- Rising **refund rate** may signal quality or mismatch issues despite topline growth.")
    lines.append("")

    lines.append("## Caveats")
    lines.append("")
    if warnings:
        for warning in warnings:
            lines.append(f"- {warning}")
    else:
        lines.append("- No major caveats detected by automatic checks.")
    lines.append("")

    if ai_explanation:
        lines.append("## AI explanation")
        lines.append("")
        lines.append(ai_explanation.strip())
        lines.append("")

    lines.append("---")
    lines.append("Generated by PromoLab")
    return "\n".join(lines)
